version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
    - method: pip
      requirements: null
      packages:
        - mkdocs
        - mkdocs-material
        - mkdocstrings[python]

mkdocs:
  configuration: mkdocs.yml

