name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .[dev]
          pip install -r docs/requirements.txt

      - name: Run tests
        run: pytest

      - name: Build package
        run: python -m build

      - name: Check built packages
        run: twine check dist/*

      - name: Build documentation
        run: sphinx-build -b html docs/source docs/build/html
